### PR TITLE
add examples for :> and :>> usage

### PR DESCRIPTION
**Pull request by goertzenator**
The examples I wish I'd had when I learned Cleff.

### CODE REVIEW

**Comment by re-xyr** [comment]
Thanks! It seems that the middle example is not of the same semantics as the other two - maybe remove it? The other two examples can be connected by something like "Either ... or ...".

**Comment by goertzenator** [comment]
Apologies, I should have done that a little more carefully as the first commit didn't connect at all with the following paragraph.

Some context on this change:  I've converted a codebase using polysemy to cleff (which went very smoothly BTW!); I understood the concepts and what I needed to do, but I just needed to see simple examples of single and multiple effect constraints... and this is what this PR adds.

**Comment by re-xyr** [comment]
Thanks, it looks better now! I think changing "... and ... mean" on the last line to "... and ... both mean" will be better; after fixing that we can get it merged.

**Comment by re-xyr** [comment]
Sorry, can't merge this for now because I'm in lockdown and have no access to my machine. I'll merge it asap once the lockdown is lifted.

**Comment by re-xyr** [comment]
Shipped in 3f7c36e - I changed the wording a bit, hope you don't mind!

**Pull request closed without merging**
